---
- name: Install prerequisites for Docker
  yum:
    name: yum-utils
    state: present
  when:
    - ansible_os_family == "RedHat"
    - ansible_host != "35.209.191.170"
- name: add repo docker
  shell: yum config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo # here it was tell if no creates the only shell cmd execute
  when:
    - ansible_host != "35.209.191.170"
    - ansible_os_family == "RedHat"


- name: Install Docker
  yum:
    name: "{{ item }}"

    state: present

  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  when:
    - ansible_os_family == "RedHat"
    - ansible_host != "35.209.191.170"


- name: Start and enable Docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Install Apache (httpd)
  yum:
    name: httpd
    state: present
  when:
    - ansible_os_family == "RedHat"
    - ansible_host != "35.209.191.170"

- name: Start and enable Apache
  service:
    name: httpd
    state: started
    enabled: yes
  when:
    - ansible_os_family == "RedHat"
    - ansible_host != "35.209.191.170"


- name: Copy index.html
  copy:
    src: files/index.html
    dest: /var/www/html/index.html
  when:
    - ansible_os_family == "RedHat"
    - ansible_host != "35.209.191.170"

- name: get buildnumber
  debug:
    msg: " {{build_number}}"
  when:
    - ansible_os_family == "RedHat"
    - ansible_host != "35.209.191.170"

- name: take image from docker hub
  command: docker pull ganesh6498/pyweb1:{{ build_number }}
  when:
    - ansible_os_family == "RedHat"
    - ansible_host != "35.209.191.170"

- name: run container
  command: docker run -it -d -p 8082:8080 ganesh6498/pyweb1:{{ build_number }}
  when:
    - ansible_os_family == "RedHat"
    - ansible_host != "35.209.191.170"

