- name: Install prerequisites for Docker
  yum:
    name: yum-utils
    state: present

- name: Install Docker
  yum:
    name: docker
    state: present

- name: Start and enable Docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Install Apache (httpd)
  yum:
    name: httpd
    state: present

- name: Start and enable Apache
  service:
    name: httpd
    state: started
    enabled: yes

- name: Copy index.html
  copy:
    src: files/index.html
    dest: /var/www/html/index.html

