---
- name: Ensure required packages are installed
  apt:
    name:
      - ca-certificates
      - curl
    state: present
    update_cache: yes
  when:
    - ansible_os_family == "Debian"
    - ansible_host != "35.209.191.170"

- name: Ensure /etc/apt/keyrings directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker GPG key
  get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
  when:
    - ansible_os_family == "Debian"
    - ansible_host != "35.209.191.170"

- name: Add Docker repository
  shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] \
    https://download.docker.com/linux/debian $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
  args:
    creates: /etc/apt/sources.list.d/docker.list
  when:
    - ansible_os_family == "Debian"
    - ansible_host != "35.209.191.170"

- name: Update apt package cache
  apt:
    update_cache: yes  
  when:
    - ansible_os_family == "Debian"
    - ansible_host != "35.209.191.170"

- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
  when:
    - ansible_os_family == "Debian"
    - ansible_host != "35.209.191.170"

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes
  when:
    - ansible_os_family == "Debian"
    - ansible_host != "35.209.191.170"

- name: Install Apache
  apt:
    name: apache2
    state: present
  when:
    - ansible_os_family == "Debian"
    - ansible_host != "35.209.191.170"

- name: Ensure Apache is running
  service:
    name: apache2
    state: started
    enabled: yes
  when:
    - ansible_os_family == "Debian"
    - ansible_host != "35.209.191.170"

- name: Copy index.html to Apache web root
  copy:
    src: files/index.html
    dest: /var/www/html/index.html
  when:
    - ansible_os_family == "Debian"
    - ansible_host != "35.209.191.170"
  ignore_errors: true

- name: Get build number
  debug:
    msg: "{{ build_number }}"

- name: Pull Docker image from Docker Hub
  community.docker.docker_image:
    name: "ganesh6498/web2:{{ build_number }}"
    source: pull
  when:
    - ansible_os_family == "Debian"
    - ansible_host != "35.209.191.170"

- name: Run container
  community.docker.docker_container:
    name: web_app
    image: "ganesh6498/web2:{{ build_number }}"
    state: started
    ports:
      - "82:80"
  when:
    - ansible_os_family == "Debian"
    - ansible_host != "35.209.191.170"


